import { Lens } from '../types/lens';
import { normalLens } from './definitions/normal';
import { bigNoseLens } from './definitions/bigNose';
import { bigEyesLens } from './definitions/bigEyes';
import { bigMouthLens } from './definitions/bigMouth';
import { wideFaceLens } from './definitions/wideFace';
import { tinyFaceLens } from './definitions/tinyFace';
import { alienLens } from './definitions/alien';
import { swirlFaceLens } from './definitions/swirlFace';
import { puppyLens } from './definitions/puppy';
import { bunnyLens } from './definitions/bunny';
import { funnyGlassesLens } from './definitions/funnyGlasses';

// Array of 50 lenses with numbered names (01, 02, ... 50)
export const ALL_50_LENSES: Lens[] = [
  // 01 to 11: Base lenses with numbers added to names
  { ...normalLens, id: 'normal', name: '01. Natural' },
  { ...bigNoseLens, id: 'big-nose', name: '02. Big Nose' },
  { ...bigEyesLens, id: 'big-eyes', name: '03. Anime Eyes' },
  { ...bigMouthLens, id: 'big-mouth', name: '04. Big Mouth' },
  { ...wideFaceLens, id: 'wide-face', name: '05. Wide Face' },
  { ...tinyFaceLens, id: 'tiny-face', name: '06. Tiny Face' },
  { ...alienLens, id: 'alien', name: '07. Alien Entity' },
  { ...swirlFaceLens, id: 'swirl-face', name: '08. Swirl Vortex' },
  { ...puppyLens, id: 'puppy', name: '09. Puppy Ears' },
  { ...bunnyLens, id: 'bunny', name: '10. Bunny Ears' },
  { ...funnyGlassesLens, id: 'funny-glasses', name: '11. Retro Glasses' },

  // 12 to 20: Funny category additions
  {
    id: 'gigachad',
    name: '12. Gigachad Jaw',
    category: 'funny',
    description: 'Chiseled ultra-sharp jawline and chin sculpt.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'fitness-outline',
    accentColor: '#F59E0B',
    config: {
      distortion: {
        type: 'pinch',
        targetRegion: 'jaw',
        intensity: 0.65,
        radius: 0.45,
      },
      colorFilter: { contrast: 1.25, saturation: 1.1 },
    },
  },
  {
    id: 'puffy-cheeks',
    name: '13. Puffy Cheeks',
    category: 'funny',
    description: 'Ultra squishy inflated balloon cheeks.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'happy-outline',
    accentColor: '#FB7185',
    config: {
      distortion: {
        type: 'bulge',
        targetRegion: 'face',
        intensity: 0.75,
        radius: 0.5,
      },
    },
  },
  {
    id: 'egg-head',
    name: '14. Egg Head',
    category: 'funny',
    description: 'Tall smooth cone-shaped forehead stretch.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'ellipse-outline',
    accentColor: '#FDE047',
    config: {
      distortion: {
        type: 'stretch_v',
        targetRegion: 'forehead',
        intensity: 0.7,
        radius: 0.55,
      },
    },
  },
  {
    id: 'cartoon-grin',
    name: '15. Cartoon Grin',
    category: 'funny',
    description: 'Wide comic book animated smile with rosy cheeks.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'happy-outline',
    accentColor: '#F43F5E',
    config: {
      distortion: {
        type: 'stretch_h',
        targetRegion: 'mouth',
        intensity: 0.6,
        radius: 0.4,
      },
      colorFilter: { saturation: 1.4, brightness: 1.05 },
    },
  },
  {
    id: 'stretch-face',
    name: '16. Long Face',
    category: 'funny',
    description: 'Extreme vertical elongation face stretch.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'swap-vertical-outline',
    accentColor: '#84CC16',
    config: {
      distortion: {
        type: 'stretch_v',
        targetRegion: 'all',
        intensity: 0.8,
        radius: 0.7,
      },
    },
  },
  {
    id: 'double-chin',
    name: '17. Double Chin',
    category: 'funny',
    description: 'Bulging chin fold and chubby lower jaw.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'body-outline',
    accentColor: '#EA580C',
    config: {
      distortion: {
        type: 'bulge',
        targetRegion: 'jaw',
        intensity: 0.7,
        radius: 0.4,
      },
    },
  },
  {
    id: 'fisheye',
    name: '18. Fisheye Lens',
    category: 'funny',
    description: 'Spherical ultra-wide optical fisheye lens bulge.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'disc-outline',
    accentColor: '#14B8A6',
    config: {
      distortion: {
        type: 'bulge',
        targetRegion: 'all',
        intensity: 0.85,
        radius: 0.8,
      },
    },
  },
  {
    id: 'bubble-head',
    name: '19. Bubble Head',
    category: 'funny',
    description: 'Giant bobblehead distortion on tiny shoulders.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'globe-outline',
    accentColor: '#EC4899',
    config: {
      distortion: {
        type: 'bulge',
        targetRegion: 'all',
        intensity: 0.9,
        radius: 0.75,
      },
    },
  },
  {
    id: 'silly-nose',
    name: '20. Silly Nose',
    category: 'funny',
    description: 'Pinocchio long pointed nose extension.',
    supportedCamera: 'both',
    effectType: 'distortion',
    iconName: 'help-circle-outline',
    accentColor: '#EAB308',
    config: {
      distortion: {
        type: 'stretch_h',
        targetRegion: 'nose',
        intensity: 0.75,
        radius: 0.35,
      },
    },
  },

  // 21 to 30: Animal category additions
  {
    id: 'kitty-cat',
    name: '21. Kitty Cat',
    category: 'animal',
    description: 'Cute feline cat ears, nose, and whiskers.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'overlay',
    iconName: 'paw-outline',
    accentColor: '#F472B6',
    config: {
      colorFilter: { tint: '#FDF2F8', brightness: 1.05 },
      animation: { wiggle: true },
    },
  },
  {
    id: 'teddy-bear',
    name: '22. Teddy Bear',
    category: 'animal',
    description: 'Soft brown furry teddy bear ears and nose.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'overlay',
    iconName: 'heart-circle-outline',
    accentColor: '#B45309',
    config: {
      colorFilter: { tint: '#FEF3C7', contrast: 1.05 },
    },
  },
  {
    id: 'fox-spirit',
    name: '23. Fox Spirit',
    category: 'animal',
    description: 'Mystical orange fox ears and golden aura.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'hybrid',
    iconName: 'flame-outline',
    accentColor: '#FF6B00',
    config: {
      colorFilter: { tint: '#FFF7ED', glow: '#FF6B00' },
      animation: { sparkle: true },
    },
  },
  {
    id: 'panda-bear',
    name: '24. Panda Bear',
    category: 'animal',
    description: 'Adorable panda bear ears and soft eye patches.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'overlay',
    iconName: 'aperture-outline',
    accentColor: '#334155',
    config: {
      colorFilter: { contrast: 1.2 },
    },
  },
  {
    id: 'froggy',
    name: '25. Froggy Eyes',
    category: 'animal',
    description: 'Big silly green frog eyes sitting atop your head.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'eye-outline',
    accentColor: '#22C55E',
    config: {
      distortion: {
        type: 'bulge',
        targetRegion: 'eyes',
        intensity: 0.6,
        radius: 0.35,
      },
      colorFilter: { tint: '#F0FDF4' },
    },
  },
  {
    id: 'lion-king',
    name: '26. Royal Lion',
    category: 'animal',
    description: 'Majestic golden lion mane and fierce glow.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'sunny-outline',
    accentColor: '#D97706',
    config: {
      colorFilter: { tint: '#FEF3C7', glow: '#D97706', contrast: 1.15 },
    },
  },
  {
    id: 'tiger-stripes',
    name: '27. Tiger Stripes',
    category: 'animal',
    description: 'Wild tiger face paint stripes and feline amber eyes.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'flash-outline',
    accentColor: '#EA580C',
    config: {
      colorFilter: { contrast: 1.3, saturation: 1.3 },
    },
  },
  {
    id: 'koala',
    name: '28. Koala Cute',
    category: 'animal',
    description: 'Fluffy gray koala ears and soft button nose.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'overlay',
    iconName: 'cloud-outline',
    accentColor: '#64748B',
    config: {
      colorFilter: { brightness: 1.04 },
    },
  },
  {
    id: 'wolf-howl',
    name: '29. Midnight Wolf',
    category: 'animal',
    description: 'Sleek silver wolf ears and glowing blue eyes.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'moon-outline',
    accentColor: '#38BDF8',
    config: {
      colorFilter: { tint: '#F0F9FF', glow: '#38BDF8' },
    },
  },
  {
    id: 'butterfly-wings',
    name: '30. Monarch Butterfly',
    category: 'animal',
    description: 'Fluttering monarch butterfly wings and sparkling antennas.',
    supportedCamera: 'front',
    requiresFrontCameraNotice: true,
    effectType: 'hybrid',
    iconName: 'flower-outline',
    accentColor: '#F97316',
    config: {
      colorFilter: { saturation: 1.25 },
      animation: { sparkle: true, pulseSpeed: 0.8 },
    },
  },

  // 31 to 40: Creature & Sci-Fi category additions
  {
    id: 'neon-cyborg',
    name: '31. Neon Cyborg',
    category: 'creature',
    description: 'Cybernetic implants with glowing laser HUD interface.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'hardware-chip-outline',
    accentColor: '#06B6D4',
    config: {
      colorFilter: { tint: '#ECFEFF', glow: '#06B6D4', contrast: 1.2 },
      animation: { pulseSpeed: 1.2 },
    },
  },
  {
    id: 'demon-horns',
    name: '32. Demon Horns',
    category: 'creature',
    description: 'Fiery crimson demon horns and burning eyes.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'flame',
    accentColor: '#DC2626',
    config: {
      colorFilter: { tint: '#FEF2F2', glow: '#DC2626', contrast: 1.3 },
    },
  },
  {
    id: 'vampire',
    name: '33. Vampire Fangs',
    category: 'creature',
    description: 'Sharp vampire fangs and gothic blood red tint.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'skull-outline',
    accentColor: '#991B1B',
    config: {
      colorFilter: { tint: '#450A0A', contrast: 1.4, saturation: 1.2 },
    },
  },
  {
    id: 'dragon-fire',
    name: '34. Dragon Fire',
    category: 'creature',
    description: 'Magma dragon scales and fiery ambient smoke particles.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'bonfire-outline',
    accentColor: '#F97316',
    config: {
      colorFilter: { tint: '#FFF7ED', glow: '#F97316', contrast: 1.25 },
      animation: { sparkle: true },
    },
  },
  {
    id: 'scifi-visor',
    name: '35. Sci-Fi Visor',
    category: 'creature',
    description: 'Futuristic robotic target tracking HUD visor.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'scan-outline',
    accentColor: '#3B82F6',
    config: {
      colorFilter: { tint: '#EFF6FF', glow: '#3B82F6' },
    },
  },
  {
    id: 'laser-eye',
    name: '36. Laser Eye',
    category: 'creature',
    description: 'Intense laser beam eyes and superhero aura.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'flash',
    accentColor: '#EF4444',
    config: {
      colorFilter: { glow: '#EF4444', contrast: 1.35 },
      animation: { pulseSpeed: 1.5 },
    },
  },
  {
    id: 'zombie',
    name: '37. Zombie Undead',
    category: 'creature',
    description: 'Creepy zombie green skin tint and hollow eye sockets.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'body',
    accentColor: '#65A30D',
    config: {
      distortion: {
        type: 'pinch',
        targetRegion: 'eyes',
        intensity: 0.5,
        radius: 0.3,
      },
      colorFilter: { tint: '#ECFDF5', contrast: 1.3, saturation: 0.7 },
    },
  },
  {
    id: 'angel-halo',
    name: '38. Angel Halo',
    category: 'creature',
    description: 'Divine glowing golden halo and heavenly starlight particles.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'sparkles',
    accentColor: '#FBBF24',
    config: {
      colorFilter: { tint: '#FFFBEB', glow: '#FBBF24', brightness: 1.1 },
      animation: { sparkle: true, pulseSpeed: 0.9 },
    },
  },
  {
    id: 'goblin',
    name: '39. Goblin Mask',
    category: 'creature',
    description: 'Mischievous goblin pointed nose and green skin.',
    supportedCamera: 'both',
    effectType: 'hybrid',
    iconName: 'bug-outline',
    accentColor: '#4D7C0F',
    config: {
      distortion: {
        type: 'stretch_h',
        targetRegion: 'nose',
        intensity: 0.65,
        radius: 0.35,
      },
      colorFilter: { tint: '#F7FEE7' },
    },
  },
  {
    id: 'cosmic-starlight',
    name: '40. Cosmic Starlight',
    category: 'creature',
    description: 'Deep space nebula aura with shimmering stardust particles.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'planet-outline',
    accentColor: '#A855F7',
    config: {
      colorFilter: { tint: '#FAF5FF', glow: '#A855F7', contrast: 1.15 },
      animation: { sparkle: true },
    },
  },

  // 41 to 50: Style & Classic category additions
  {
    id: 'synthwave-80s',
    name: '41. Synthwave 80s',
    category: 'style',
    description: 'Retro 1980s neon grid overlay with CRT magenta glow.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'tv-outline',
    accentColor: '#EC4899',
    config: {
      colorFilter: { tint: '#FDF2F8', glow: '#EC4899', contrast: 1.3, saturation: 1.35 },
    },
  },
  {
    id: 'cyberpunk-grid',
    name: '42. Cyberpunk Grid',
    category: 'style',
    description: 'Electric cyan and neon blue high-contrast aesthetic.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'grid-outline',
    accentColor: '#0EA5E9',
    config: {
      colorFilter: { tint: '#F0F9FF', glow: '#0EA5E9', contrast: 1.35 },
    },
  },
  {
    id: 'golden-sunset',
    name: '43. Golden Sunset',
    category: 'style',
    description: 'Warm golden hour sunset light leak and soft flare.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'partly-sunny-outline',
    accentColor: '#F59E0B',
    config: {
      colorFilter: { tint: '#FEF3C7', brightness: 1.08, contrast: 1.1 },
    },
  },
  {
    id: 'vintage-70s',
    name: '44. Vintage 70s',
    category: 'style',
    description: 'Warm nostalgic 1970s film photo tint and faded grain.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'camera',
    accentColor: '#D97706',
    config: {
      colorFilter: { tint: '#FEF3C7', contrast: 0.95, brightness: 1.04 },
    },
  },
  {
    id: 'vaporwave',
    name: '45. Vaporwave Vibe',
    category: 'style',
    description: 'Dreamy pastel pink and mint green aesthetic filter.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'color-palette-outline',
    accentColor: '#D946EF',
    config: {
      colorFilter: { tint: '#FDF4FF', contrast: 1.1, saturation: 1.25 },
    },
  },
  {
    id: 'sunset-aura',
    name: '46. Sunset Aura',
    category: 'style',
    description: 'Vibrant indigo and sunset purple dual lighting.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'rose-outline',
    accentColor: '#8B5CF6',
    config: {
      colorFilter: { tint: '#F5F3FF', glow: '#8B5CF6', contrast: 1.2 },
    },
  },
  {
    id: 'diamond-glitter',
    name: '47. Diamond Glitter',
    category: 'style',
    description: 'Luxurious diamond sparkle glitter effect.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'diamond-outline',
    accentColor: '#E2E8F0',
    config: {
      colorFilter: { brightness: 1.1, contrast: 1.15 },
      animation: { sparkle: true, pulseSpeed: 1.1 },
    },
  },
  {
    id: 'matrix-code',
    name: '48. Matrix Code',
    category: 'style',
    description: 'Falling green digital matrix code rain color tint.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'code-slash-outline',
    accentColor: '#10B981',
    config: {
      colorFilter: { tint: '#ECFDF5', glow: '#10B981', contrast: 1.4 },
    },
  },
  {
    id: 'cinema-noir',
    name: '49. Cinema Noir',
    category: 'classic',
    description: 'High-contrast classic black and white film look.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'film-outline',
    accentColor: '#94A3B8',
    config: {
      colorFilter: { saturation: 0, contrast: 1.4, brightness: 0.98 },
    },
  },
  {
    id: 'thermal-heat',
    name: '50. Thermal Heat',
    category: 'classic',
    description: 'Infrared thermal heat vision camera simulation.',
    supportedCamera: 'both',
    effectType: 'color_filter',
    iconName: 'thermometer-outline',
    accentColor: '#EF4444',
    config: {
      colorFilter: { tint: '#FEF2F2', contrast: 1.5, saturation: 1.6 },
    },
  },
];
